# Generated by Django 4.2.5 on 2023-09-14 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Club Name")),
                (
                    "display_name",
                    models.CharField(
                        max_length=255, verbose_name="Display Name"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="nearest town",
                        max_length=255,
                        null=True,
                        verbose_name="Session Location",
                    ),
                ),
